version: '3.8'

volumes:
  dependency-track:
  dependency-track-npm:
  db:
    driver: local
  db-npm:
    driver: local

services:
  nginx-reverse-proxy:
    image: 'nginx:1.25.3'
    depends_on:
      - dtrack-frontend
      - dtrack-apiserver
      - dtrack-npm-frontend
      - dtrack-npm-apiserver
    volumes:
      - '/etc/letsencrypt:/etc/letsencrypt:ro'
      - '/usr/local/lib/deptrack/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
    ports:
      - '443:443'
    restart: unless-stopped

  dtrack-apiserver:
    image: 'dependencytrack/apiserver:4.10.1'
    environment:
    # The Dependency-Track container can be configured using any of the
    # available configuration properties defined in:
    # https://docs.dependencytrack.org/getting-started/configuration/
    # All properties are upper case with periods replaced by underscores.
    #
    # Database Properties
     - ALPINE_DATABASE_MODE=external
     - ALPINE_DATABASE_URL=jdbc:postgresql://dtrack-db:5432/dtrack
     - ALPINE_DATABASE_DRIVER=org.postgresql.Driver
     - ALPINE_DATABASE_USERNAME=dtrack
     - ALPINE_DATABASE_PASSWORD=dtrack
     - ALPINE_DATABASE_POOL_ENABLED=true
     - ALPINE_DATABASE_POOL_MAX_SIZE=20
     - ALPINE_DATABASE_POOL_MIN_IDLE=2
     - ALPINE_DATABASE_POOL_IDLE_TIMEOUT=300000
     - ALPINE_DATABASE_POOL_MAX_LIFETIME=600000
    # Cross-Origin Resource Sharing (CORS) Headers
     - ALPINE_CORS_ENABLED=true
     - ALPINE_CORS_ALLOW_ORIGIN=https://dependencytrack.avega.io
     - ALPINE_CORS_ALLOW_METHODS=GET, POST, PUT, DELETE, OPTIONS
     - ALPINE_CORS_ALLOW_HEADERS=Origin, Content-Type, Authorization, X-Requested-With, Content-Length, Accept, Origin, X-Api-Key, X-Total-Count, *
     - ALPINE_CORS_EXPOSE_HEADERS=Origin, Content-Type, Authorization, X-Requested-With, Content-Length, Accept, Origin, X-Api-Key, X-Total-Count
     - ALPINE_CORS_ALLOW_CREDENTIALS=true
     - ALPINE_CORS_MAX_AGE=3600
    mem_reservation: '5g'
    mem_limit: '6g'
    volumes:
      - 'dependency-track:/data'
    restart: unless-stopped

  dtrack-frontend:
    image: 'dependencytrack/frontend:4.9.1'
    depends_on:
      - dtrack-apiserver
    environment:
      # The base URL of the API server.
      # NOTE:
      #   * This URL must be reachable by the browsers of your users.
      #   * The frontend container itself does NOT communicate with the API server directly, it just serves static files.
      #   * When deploying to dedicated servers, please use the external IP or domain of the API server.
      - API_BASE_URL=https://dependencytrack.avega.io
    restart: unless-stopped

  dtrack-db:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=dtrack
      - POSTGRES_PASSWORD=dtrack
    volumes:
      - db:/var/lib/postgresql/data

  dtrack-npm-apiserver:
    image: 'dependencytrack/apiserver:4.10.1'
    environment:
      # The Dependency-Track container can be configured using any of the
      # available configuration properties defined in:
      # https://docs.dependencytrack.org/getting-started/configuration/
      # All properties are upper case with periods replaced by underscores.
      #
      # Database Properties
      - ALPINE_DATABASE_MODE=external
      - ALPINE_DATABASE_URL=jdbc:postgresql://dtrack-npm-db:5432/dtracknpm
      - ALPINE_DATABASE_DRIVER=org.postgresql.Driver
      - ALPINE_DATABASE_USERNAME=dtracknpm
      - ALPINE_DATABASE_PASSWORD=dtracknpm
      - ALPINE_DATABASE_POOL_ENABLED=true
      - ALPINE_DATABASE_POOL_MAX_SIZE=20
      - ALPINE_DATABASE_POOL_MIN_IDLE=2
      - ALPINE_DATABASE_POOL_IDLE_TIMEOUT=300000
      - ALPINE_DATABASE_POOL_MAX_LIFETIME=600000
      # Cross-Origin Resource Sharing (CORS) Headers
      - ALPINE_CORS_ENABLED=true
      - ALPINE_CORS_ALLOW_ORIGIN=https://dependencytrack-npm.avega.io
      - ALPINE_CORS_ALLOW_METHODS=GET, POST, PUT, DELETE, OPTIONS
      - ALPINE_CORS_ALLOW_HEADERS=Origin, Content-Type, Authorization, X-Requested-With, Content-Length, Accept, Origin, X-Api-Key, X-Total-Count, *
      - ALPINE_CORS_EXPOSE_HEADERS=Origin, Content-Type, Authorization, X-Requested-With, Content-Length, Accept, Origin, X-Api-Key, X-Total-Count
      - ALPINE_CORS_ALLOW_CREDENTIALS=true
      - ALPINE_CORS_MAX_AGE=3600
    mem_reservation: '5g'
    mem_limit: '6g'
    volumes:
      - 'dependency-track-npm:/data'
    restart: unless-stopped

  dtrack-npm-frontend:
    image: 'dependencytrack/frontend:4.9.1'
    depends_on:
      - dtrack-npm-apiserver
    environment:
      # The base URL of the API server.
      # NOTE:
      #   * This URL must be reachable by the browsers of your users.
      #   * The frontend container itself does NOT communicate with the API server directly, it just serves static files.
      #   * When deploying to dedicated servers, please use the external IP or domain of the API server.
      - API_BASE_URL=https://dependencytrack-npm.avega.io
    restart: unless-stopped

  dtrack-npm-db:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=dtracknpm
      - POSTGRES_PASSWORD=dtracknpm
    volumes:
      - db-npm:/var/lib/postgresql/data
